apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 879772956301.dkr.ecr.eu-central-1.amazonaws.com/lecture-gateway:latest 
#          image: username/gateway:latest
          ports:
            - containerPort: 8080
